version: '3'
services:
  node:
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
      - /opt/app/node_modules

  db:
    image: mongo
    expose:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
